#!/bin/bash

# Copyright 2011 Josh Beitelspacher
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

REBOOT_HOME=$(dirname $(readlink -f $0))

JAVA_HOME=$(dirname $(readlink -f $(which java)))/../..

exec java -cp "${JAVA_HOME}/lib/tools.jar:${REBOOT_HOME}/core" "-Dcom.netbeetle.reboot.home=${REBOOT_HOME}" com.netbeetle.reboot.core.Reboot "$@"

# Use the following line to debug
#exec java -agentlib:jdwp=transport=dt_socket,address=localhost:9009,server=y,suspend=y -cp "${JAVA_HOME}/lib/tools.jar:${REBOOT_HOME}/core" "-Dcom.netbeetle.reboot.home=${REBOOT_HOME}" com.netbeetle.reboot.core.Reboot "$@"
