#!/bin/bash

# Copyright 2011 Josh Beitelspacher
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cd $(dirname $(readlink -f $0))

MAVEN_BASE=~/.reboot/cache/http/repo2.maven.org/maven2
JETTY_BASE=${MAVEN_BASE}/org/eclipse/jetty
JETTY_VERSION=7.4.1.v20110513
JETTY_CLASSPATH=${MAVEN_BASE}/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar
JETTY_CLASSPATH=${JETTY_CLASSPATH}:${JETTY_BASE}/jetty-continuation/${JETTY_VERSION}/jetty-continuation-${JETTY_VERSION}.jar
JETTY_CLASSPATH=${JETTY_CLASSPATH}:${JETTY_BASE}/jetty-http/${JETTY_VERSION}/jetty-http-${JETTY_VERSION}.jar
JETTY_CLASSPATH=${JETTY_CLASSPATH}:${JETTY_BASE}/jetty-io/${JETTY_VERSION}/jetty-io-${JETTY_VERSION}.jar
JETTY_CLASSPATH=${JETTY_CLASSPATH}:${JETTY_BASE}/jetty-util/${JETTY_VERSION}/jetty-util-${JETTY_VERSION}.jar
JETTY_CLASSPATH=${JETTY_CLASSPATH}:${JETTY_BASE}/jetty-server/${JETTY_VERSION}/jetty-server-${JETTY_VERSION}.jar

mkdir -p target/native

javac -classpath ${JETTY_CLASSPATH} -d target/native/ src/main/java/org/example/HelloWorld.java

exec java -classpath ${JETTY_CLASSPATH}:target/native/ org.example.HelloWorld
